[package]
name = "fdtd"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
bytemuck = "1.24.0"
chrono = "0.4.42"
clap = { version = "4.5.50", features = ["derive"] }
color-eyre = "0.6.5"
derive_more = { version = "2.0.1", features = ["debug"] }
dotenvy = "0.15.7"
eframe = { version = "0.33.0", default-features = false, features = ["accesskit", "default_fonts", "wayland", "x11", "wgpu"] }
egui = "0.33.0"
egui-wgpu = { version = "0.33.0", features = ["default"] }
egui_plot = "0.34.0"
hecs = { version = "0.10.5", features = ["macros"] }
image = "0.25.8"
nalgebra = { version = "0.34.1", features = ["bytemuck"] }
num = "0.4.3"
palette = { version = "0.7.6", features = ["named", "bytemuck"] }
parking_lot = "0.12.5"
parry3d = "0.25.2"
thiserror = "2.0.17"
tobj = "4.0.3"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
type-map = "0.5.1"
wgpu = "27.0.1"
