[workspace]
resolver = "2"
members = ["fdtd-app", "fdtd-build"]

[patch.crates-io]
eframe = { git = "https://github.com/jgraef/egui.git", branch = "switch/wgpu-stencil-buffer" }
egui = { git = "https://github.com/jgraef/egui.git", branch = "switch/wgpu-stencil-buffer" }
egui-wgpu = { git = "https://github.com/jgraef/egui.git", branch = "switch/wgpu-stencil-buffer" }
egui-winit = { git = "https://github.com/jgraef/egui.git", branch = "switch/wgpu-stencil-buffer" }
emath = { git = "https://github.com/jgraef/egui.git", branch = "switch/wgpu-stencil-buffer" }
