[package]
name = "nec-file"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
bitflags = "2.10.0"
nalgebra = "0.34.1"
thiserror = "2.0.17"

[dev-dependencies]
clap = { version = "4.5.53", features = ["derive"] }
color-eyre = "0.6.5"
