[package]
name = "fdtd-build"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "0.6.12"
heck = "0.5.0"
palette = "0.7.6"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tracing = "0.1.41"
